config/routes.rb
Rails.application.routes.draw do
  root 'top#index'

  devise_for :users
  resources :users
  resources :favorites
  resources :restaurants do
     collection do
       post 'draw'
     end
  end
end

app/models/favorite.rb
# == Schema Information
#
# Table name: favorites
#
#  id            :integer          not null, primary key
#  user_id       :integer          not null
#  restaurant_id :integer          not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Favorite < ActiveRecord::Base
	belongs_to :user
	belongs_to :restaurant
end

app/models/restaurant.rb
# == Schema Information
#
# Table name: restaurants
#
#  id              :integer          not null, primary key
#  gid             :string(255)      not null
#  name            :string(255)      not null
#  url             :string(255)      not null
#  latitude        :float(24)
#  longitude       :float(24)
#  address         :string(255)      not null
#  opentime        :string(255)
#  areaname_s      :string(255)      not null
#  category_name_l :string(255)      not null
#  image_url_1     :string(255)
#  image_url_2     :string(255)
#

class Restaurant < ActiveRecord::Base
  scope :around, ->(longitude, latitude) {
    long_to_m = 3000.0/111136.0
    lati_to_m = 3000.0/111325.0
    long_range = (longitude - long_to_m)..(longitude + long_to_m)
    lati_range = (latitude - lati_to_m)..(latitude + lati_to_m)
    where(longitude: long_range, latitude: lati_range)
  }

  def self.build_from_api(json)
    image_urls = json.delete(:image_url)
    code = json.delete(:code)
    code[:category_name_l].keep_if{|c| c.is_a?(String) }
    code[:category_name_l].delete("居酒屋")
    code[:category_name_l].delete("ダイニングバー・バー・ビアホール")
    code[:category_name_l].delete("ビストロ")

    json[:gid] = json.delete(:id)
    json[:image_url_1] = image_urls[:shop_image1]
    json[:image_url_2] = image_urls[:shop_image2]
    json[:areaname_s] = code[:areaname_s]
    json[:category_name_l] = code[:category_name_l].join(",")
    new(json.extract!(*column_names))
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :favorites
  has_many :restaurants, through: :favorites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/favorites_controller.rb
class FavoritesController < BaseController
  def index
  end

  def new
    @restaurants = GuruNaviApi.restaurants(query: params[:search]) if params[:search]
  end

  def create
    restaurant = Restaurant.find_by(gid: params[:gid])
    restaurant||= GuruNaviApi.restaurants(query: { id: params[:gid] }).first
    current_user.favorites.find_or_create_by!(restaurant: restaurant)
    redirect_to root_path, notice: "#{restaurant.name}をお気に入りに追加しました"
  end

  def destroy
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
  end

  def draw
    longitude = params[:data][:longitude].to_f
    latitude = params[:data][:latitude].to_f
    ids = current_user.restaurants.around(longitude, latitude).pluck(:id)
    render :empty and return if ids.empty?

    @restaurant = Restaurant.find(ids.sample)

    render layout: false
  end
end

app/controllers/top_controller.rb
class TopController < BaseController
  def index
    @restaurants = current_user.restaurants.page(params[:page]).order(id: :desc)
  end
end

app/controllers/users_controller.rb
class UsersController < BaseController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    messages = resource.errors.full_messages.each do |errmsg|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{errmsg}
      </div>
      EOF
    end
    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<h1>FavoritesController#index</h1>
<p>Find me in app/views/favorites_controller/index.html.erb</p>

app/views/favorites/new.html.erb
<%= form_for('search', method: :get, html: { class: "form-horizontal" }) do |f| %>
  <div class="input-group">
    <%= f.text_field :freeword, class: "form-control", placeholder: "フリーワード検索", value: params.fetch(:search, {})[:freeword] %>
    <%= f.hidden_field :latitude %>
    <%= f.hidden_field :longitude %>
    <%= f.hidden_field :range, value: 5 %>
    <span class="input-group-btn">
      <%= f.submit value: "検索", id: "search_submit", class: "btn btn-default", disabled: true %>
    </span>
  </div>
<% end %>

<% if @restaurants %>
<br>
<div class="panel panel-default">
  <div class="panel-heading">検索結果</div>
  <div class="panel-body">
    <%= table_for @restaurants, html: { class: "table table-striped" } do -%>
      <% column(title: "店舗名") do |c| %>
        <% content_tag :div do %>
          <% link_to(c.name, c.url, target: "_blank") + "<br>".html_safe + content_tag(:small, c.category_name_l) %>
        <% end %>
      <% end %>
      <% column(title: "", html: { td: { style: "text-align: right;" }}) do |c| %>
        <% link_to("追加", favorites_path(gid: c.gid), method: :post, class: "btn btn-primary") %>
      <% end %>
    <% end %>
  </div>
</div>
<% end %>

<script>
if (navigator.geolocation) {
  navigator.geolocation.getCurrentPosition(function(position) {
    $("#search_latitude").val(position.coords.latitude);
    $("#search_longitude").val(position.coords.longitude);
    $("#search_submit").removeAttr("disabled");
  });
} else {
  $("#search_submit").removeAttr("disabled");
}
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>日刊もぐもぐ</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path do %>
        <%= image_tag "logo_s.png" %>
      <% end %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "新しいお店を登録する", new_favorite_path %></li>
          <li><%= link_to "今日のお店を決める", restaurants_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              <%= current_user.email %><span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'アカウント', edit_user_path(current_user) %></li>
              <li><%= link_to 'サインアウト', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'サインアップ', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>


<div class="container">
<% flash.each do |key, value| %>
  <div class="alert alert-info alert-dismissible fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
    <%= content_tag(:div, value, class: "#{key}") %>
  </div>
<% end %>

<%= yield %>
</div>

</body>
</html>

app/views/restaurants/draw.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">今日のランチはここに決定しました</h3>
  </div>
  <div class="panel-body">
  	<table class="table table-striped table-hover ">
      <tbody>
      	<tr>
      		<td>
      			<%= link_to @restaurant.name , @restaurant.url %>
      		</td>
    		</tr>
    		<tr>
    		<td>
        <%= @restaurant.category_name_l %>
        </td>
        </tr>
    		<tr>
      		<td>
      			ランチタイム<br>
      			<%= @restaurant.opentime %>
      		</td>
    		</tr>
    		<tr>
      		<td>
        	  <% if @restaurant.image_url_1? && @restaurant.image_url_1 != "{}" %>
		        <%= image_tag @restaurant.image_url_1 , :size => '200x200' %>
		        <% end %>
		        <% if @restaurant.image_url_2? && @restaurant.image_url_2 != "{}" %>
		        <%= image_tag @restaurant.image_url_2 , :size => '200x200' %>
		        <% end %>
      		</td>
      	</tr>
      </tbody>
    </table>
  </div>
</div>

app/views/restaurants/empty.html.erb
<h1>まだお店の登録がありません </h1>

<%= link_to "新しいお店を登録する", new_favorite_path , class: "btn btn-primary" %>

app/views/restaurants/index.html.erb
<div id="main-content">
  <div style="text-align: center; padding-top: 50px;">Now loading...</div>
</div>

<script>
navigator.geolocation.getCurrentPosition(function(position) {
  $("#search_latitude").val(position.coords.latitude);
  $("#search_longitude").val(position.coords.longitude);
  $.post("<%= draw_restaurants_path %>", { data: position.coords }).done(function(data) {
    $("#main-content").html(data);
  });
});
</script>

app/views/top/index.html.erb
<table class="table table-striped table-hover ">
  <tbody>
<% @restaurants.each do |restaurant| %>
    <tr class="info">
      <td><%= link_to restaurant.name , restaurant.url, target: "_blank" %></td>
      </tr><tr>
      <td>
        <small>
          ランチタイム<br>
      	  <%=raw restaurant.opentime %>
        </small>
      </td>
      </tr><tr>
      <td>
      <%= restaurant.category_name_l %>
      </td>
      </tr><tr>
      <td>
      	<% if restaurant.image_url_1? && restaurant.image_url_1 != "{}" %>
        <%= image_tag restaurant.image_url_1 , :size => '128x128' %>
        <% end %>
        <% if restaurant.image_url_2? && restaurant.image_url_2 != "{}" %>
        <%= image_tag restaurant.image_url_2 , :size => '128x128' %>
        <% end %>
      </td>
      </tr>
<% end %>
</tbody>
</table>

<%= paginate @restaurants %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email, "メールアドレス" %><br>
    <%= f.text_field :email %>
  </div>

  <br>

  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>アカウント情報</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>